import { BASE_PATH } from "@/lib/paths";
import type { MetadataRoute } from "next";

/**
 * Icons are committed PNGs generated by `npm run icons` from `src/app/icon.svg`.
 * iOS ignores an SVG-only icon set, and a launcher crops a maskable icon to a
 * circle, so the maskable variants carry an opaque background and a safe zone.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Kitchen family recipes",
    short_name: "Kitchen",
    description: "Private family recipe box",
    start_url: `${BASE_PATH}/recipes`,
    scope: `${BASE_PATH}/`,
    display: "standalone",
    background_color: "#faf6f0",
    theme_color: "#faf6f0",
    icons: [
      { src: `${BASE_PATH}/icon-192.png`, sizes: "192x192", type: "image/png", purpose: "any" },
      { src: `${BASE_PATH}/icon-512.png`, sizes: "512x512", type: "image/png", purpose: "any" },
      {
        src: `${BASE_PATH}/icon-192-maskable.png`,
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: `${BASE_PATH}/icon-512-maskable.png`,
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
      { src: `${BASE_PATH}/icon.svg`, sizes: "any", type: "image/svg+xml" },
    ],
    shortcuts: [
      {
        name: "Add a recipe",
        short_name: "Add",
        url: `${BASE_PATH}/recipes/new`,
        icons: [{ src: `${BASE_PATH}/icon-192.png`, sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Recipes",
        short_name: "Recipes",
        url: `${BASE_PATH}/recipes`,
        icons: [{ src: `${BASE_PATH}/icon-192.png`, sizes: "192x192", type: "image/png" }],
      },
      {
        name: "Cookbooks",
        short_name: "Cookbooks",
        url: `${BASE_PATH}/cookbooks`,
        icons: [{ src: `${BASE_PATH}/icon-192.png`, sizes: "192x192", type: "image/png" }],
      },
    ],
  };
}
