-- DEPRECATED: legacy Mom/Dad/Alex seed SQL
--
-- Do not run this file. Sample content is seeded via Prisma:
--
--   cd kitchen
--   npm run db:purge-seed-users   # remove legacy @laus.family users (once)
--   npm run db:seed:demo          # demo@lovethelaus.com + 8 recipes / 3 cookbooks
--
-- Requires SUPABASE_SERVICE_ROLE_KEY and DEMO_USER_PASSWORD in .env.
-- See supabase/AUTH.md and README.md.
