export const COMMON_INGREDIENTS = [
  "all-purpose flour",
  "baking powder",
  "baking soda",
  "bananas",
  "basil",
  "beef",
  "black pepper",
  "bread",
  "broccoli",
  "brown sugar",
  "butter",
  "carrots",
  "cheddar cheese",
  "chicken breast",
  "chicken thighs",
  "cinnamon",
  "cocoa powder",
  "coconut oil",
  "cornstarch",
  "cream cheese",
  "eggs",
  "garlic",
  "ground beef",
  "heavy cream",
  "honey",
  "lemon",
  "milk",
  "mushrooms",
  "olive oil",
  "onion",
  "oregano",
  "paprika",
  "parmesan",
  "parsley",
  "pasta",
  "potatoes",
  "rice",
  "salt",
  "salmon",
  "sour cream",
  "soy sauce",
  "spinach",
  "sugar",
  "tomatoes",
  "vanilla extract",
  "vegetable oil",
  "yogurt",
] as const;
